services:

  postgres:
    container_name: checklist-db
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: checklist
    networks:
      - checklist-network

  backend:
    container_name: checklist-backend
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/checklist
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      JWT_SECRET: minha-chave-super-secreta-checklist-promotores-2026
      JWT_EXPIRATION: 86400000
    networks:
      - checklist-network

  frontend:
    container_name: checklist-frontend
    build: ./checklist-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - checklist-network

volumes:
  postgres_data:
  uploads_data:

networks:
  checklist-network:
    driver: bridge
